source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Soracom_Example', :exclusive => true do
  pod "Soracom", :path => "../"
end

target 'Soracom_Tests', :exclusive => true do
  pod "Soracom", :path => "../"
end
